### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by AndreyRGW** [Mangio621/Mangio-RVC-Fork#10]
```

Traceback (most recent call last):
  File "C:\WBC\Mangio-RVC-Fork\extract_f0_print.py", line 29, in <module>
    extraction_crepe_hop_length = int(sys.argv[4])
IndexError: list index out of range

```
This error appears at the beginning of training, but it seems that it does not affect the training, as models are successfully saved and used.

I used last commit 623b4553b60131b2f151bbbdfc32d2e1b4d75da5, 40k, pitch guidance - true, v2, mangio-crepe, crepe hop lenght - 64, one-click training.

**Comment by Mangio621** [comment]
Are you using the GUI or my own CLI interface? Looks like a flag argument parsing error.

**Comment by AndreyRGW** [comment]
> Are you using the GUI or my own CLI interface? Looks like a flag argument parsing error.

I'm using GUI

**Comment by Mangio621** [comment]
Pushed a fix. Let me know if it works.

**Comment by AndreyRGW** [comment]
> Pushed a fix. Let me know if it works.

Yeah, the error is gone
