### ISSUE TITLE
Preprocess.log error when training 

### ISSUE THREAD

**Issue by ZKekko487** [Mangio621/Mangio-RVC-Fork#128]
Long story short, when i try to train in cmd gives me this error the preprocess.log:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\{USER}\\Documents\\Music\\Mangio-RVC-v23.7.0/logs/{FOLDERNAME}/preprocess.log'
what should i do? the preprocess.log files is empty.

**Comment by tonycstech** [comment]
Same problem. No solution
