### ISSUE TITLE
Paperspace error on the newest version

### ISSUE THREAD

**Issue by Mojobones** [Mangio621/Mangio-RVC-Fork#14]
Trying to run both "make run-ui" and "make run-cli" give this error as of the most recent version:

> python infer-web.py --paperspace --pycmd python
> Use Language: en_US
> Traceback (most recent call last):
>   File "/notebooks/Mangio-RVC-Fork/infer-web.py", line 96, in <module>
>     class ToolButton(gr.Button, gr.components.FormComponent):
> AttributeError: module 'gradio.components' has no attribute 'FormComponent'

**Comment by Mojobones** [comment]
Looks like the problem is gradio, doing 'pip install gradio==3.23' to downgrade fixes it.

**Comment by Mojobones** [comment]
Fixed with most recent pull requests, so closing this.

**Comment by Limbicnation** [comment]
> 

This worked for me. Thank you!
