### ISSUE TITLE
[Help me!] All Training attempts generated the same voice.

### ISSUE THREAD

**Issue by Ahm3dRN** [Mangio621/Mangio-RVC-Fork#204]
I've been trying to train my own model on a dataset I gathered.
I used more than one person's voice, I first tried creating a model of a voice the dataset was 12 minutes of audio with 50 epochs the voice was nothing near. then I tried 100 epochs same exact voice. I changed the dataset to a different person as a different model and it's the same exact voice again. I tried a different dataset I used this time for 5x 2 min audio files. all the audio files are of good quality.
I did this with 5 different models 5 different datasets (voices) and ranging epochs of 50-200 and they all generated the same exact voice regardless. I'm really new to this I need help to figure out what's wrong.

I'm running on NVIDIA GeForce GTX 1660 SUPER

**Comment by alantero** [comment]
Did you manage to solve this problem?

**Comment by Ahm3dRN** [comment]
> Did you manage to solve this problem?

Yes I just downloaded and installed a stable version from the hugging face repo. I ended up using the main repo.

**Comment by Dubita** [comment]
Thank you so much for helping! I was getting crazy all day trying to fix this

Edit: After 2 succesfully trained models, the third model got the same voice as before the main repo. I will try to test a few more things
