### ISSUE TITLE
how do you generate audio?

### ISSUE THREAD

**Issue by SpaceMageWhatever** [Mangio621/Mangio-RVC-Fork#3]
im so confused, the instructions are ASS, i somehow figured out how to load a model, but how do i type some text, with the model i have, to then generate audio? or is this something the tool can't do? 

i hope im not the only one who finds this whole audio stuff a nightmare, i didnt struggle this much when i had to find a gui for stable diffusion, but trying to find a text to audio ai tool makes me want to die inside

i want something like elven labs or whatever it was called

**Comment by tony-rsrv** [comment]
This is not a audio synthesis tool, it is an audio conversion tool. It takes audio in and converts it to the model you provided. So no, the instructions are not _ASS_, you just don't understand the difference between synthesis and conversion.

**Comment by Mangio621** [comment]
This and the original RVC repo is not a TTS conversion tool. It is an audio->audio conversion software. Not text->audio.
