### ISSUE TITLE
Using Crepe for training just hangs forever

### ISSUE THREAD

**Issue by lucellent** [Mangio621/Mangio-RVC-Fork#5]
<img width="894" alt="Screenshot_52" src="https://github.com/Mangio621/Mangio-RVC-Fork/assets/38135928/058e7a80-5770-47b7-aba5-4c8267d026e5">

This is what happens after I try to train with crepe. My dataset is only 10 minutes and my specs are 3070 8GB and 64GB RAM.
Something keeps using all of my CPU and GPU during this stage (second stage) and nothing happens for hours. I left it for 4-6 hours but nothing, it still stayed the same.

Tried with higher values of crepe but no change

**Comment by Mangio621** [comment]
Are you running the latest version of this repo? It seems mangio-crepe is acting weird. Have you tried feature extraction with the normal "crepe"? In the newest repo version, there is 2 crepe versions to try out for feature extraction.

**Comment by lucellent** [comment]
> 

I believe I installed it 3-4 days ago, is there anything more recent?

**Comment by lucellent** [comment]
<img width="872" alt="Screenshot_53" src="https://github.com/Mangio621/Mangio-RVC-Fork/assets/38135928/01c0aaf7-afa8-46a7-8596-6e55b03c121c">

This message pops up now, after I downloaded the repo again and replaced it in the current folder, even when I have onnxruntime installed (and made sure because I installed it again)

**Comment by lucellent** [comment]
Tried both mangio and regular crepe but both give me BSOD (Video Memory Management Internal), regardless of the value

**Comment by lucellent** [comment]
@Mangio621 any idea why the BSOD might be happening? Has this been addressed in any of the newer releases

**Comment by Mangio621** [comment]
> @Mangio621 any idea why the BSOD might be happening? Has this been addressed in any of the newer releases

I'm not too sure. This problem unfortunately is too vague as i do not have specific traceback error logs to refer to. So it could be a number of things, like dependencies, gpu card recognition, cuda etc. Could even be GPU drivers. Can be too many things. Alot of people training with crepe are doing fine as they aren't training locally and using instead cloud machines. I've mentioned in the readme that crepe training is not ideal on local systems as there seems to be some cuda mishaps. If you wish to train with crepe, i recommend using runpod, paperspace or colab.

**Comment by Mangio621** [comment]
Another thing to mention is how many workers you are running. Aim for lower amount of workers.

**Comment by lucellent** [comment]
@Mangio621 not sure if this is the same as workers, but looks like I managed to fix it

The default "Number of CPU processes used for pitch extraction and data processing:" was 16, which was too much

I set it to 4 and now it works weell
