### ISSUE TITLE
question: how often do I generate the feature index? once per training set, or  after each training session?

### ISSUE THREAD

**Issue by protocolGITHUB** [Mangio621/Mangio-RVC-Fork#6]
Great program/fork!

How often do I need to train the feature index? once to scan in all the training images, or after every model training session?

ie: I train my model for 500 epochs, grab the .pth and .index, and infer on my local pc.  I decide I want to train my model some more, and do another 500 epochs.  Do I now need to regenerate the feature index after the additional model training, or is the index only related to the model training images, and doesn't need to be regenerated unless the training set/images change?

thx!

**Comment by Mangio621** [comment]
I found that you do not need to train the feature index over and over. It is a one time occurrence, as the feature index training trains on the feature extraction process, not anything to do with saved optimizer states.
