### ISSUE TITLE
formanting.txt is missing

### ISSUE THREAD

**Issue by BK-Morpheus** [Mangio621/Mangio-RVC-Fork#61]
Any time I try to train a model, this error get's thrown out, as soon, as I click "process data" in the train tab (running web-ui locally on windows pc):

`runtime\python.exe trainset_preprocess_pipeline_print.py D:\Benny\Appz\Audiotools\RVC-beta\voice\Staiy 40000 11 E:\RVC-mangio/logs/mi-test False
Traceback (most recent call last):
  File "E:\RVC-mangio\trainset_preprocess_pipeline_print.py", line 27, in <module>
    with open("formanting.txt", "r") as fvf:
FileNotFoundError: [Errno 2] No such file or directory: 'formanting.txt'`

**Comment by kalomaze** [comment]
Fixed by https://github.com/Mangio621/Mangio-RVC-Fork/commit/3295f324bdce4215f47708d96e513b84687c9e9f
