### ISSUE TITLE
Hybrid feature extraction having 'pm' in the set causes feature extraction failure

### ISSUE THREAD

**Issue by Mojobones** [Mangio621/Mangio-RVC-Fork#7]
Small issue, but if using Hybrid for feature extraction it seems that including 'pm' causes the feature extraction to fail. 

Ex:

hybrid[pm+harvest+crepe]

Will result in the error "AttributeError: 'FeatureInput' object has no attribute 'sr'"

But

hybrid[dio+harvest+crepe] was seemingly successful.

**Comment by Mangio621** [comment]
Ah i see. Looks like i need to us fr instead of sr. Naming conventions on the feature extraction typa thing. Okay, for now dont use PM until i have the time to fix it. Working on a different project as of now thus why i havent been uploading much to this fork as of recent.

**Comment by Mangio621** [comment]
Fixed the self.sr issue on pm.
