### ISSUE TITLE
ERROR: Could not build wheels for fairseq, which is required to install pyproject.toml-based projects while install requirements

### ISSUE THREAD

**Issue by ZarBoy68** [Mangio621/Mangio-RVC-Fork#8]
copying fairseq\examples\wav2vec\unsupervised\kaldi_self_train\st\local\prepare_lm.sh -> build\lib.win-amd64-cpython-310\fairseq\examples\wav2vec\unsupervised\kaldi_self_train\st\local
      copying fairseq\examples\wav2vec\unsupervised\kaldi_self_train\st\local\score.sh -> build\lib.win-amd64-cpython-310\fairseq\examples\wav2vec\unsupervised\kaldi_self_train\st\local
      copying fairseq\examples\wav2vec\unsupervised\kaldi_self_train\st\local\show_wer.sh -> build\lib.win-amd64-cpython-310\fairseq\examples\wav2vec\unsupervised\kaldi_self_train\st\local
      copying fairseq\examples\wav2vec\unsupervised\kaldi_self_train\st\local\train_subset_lgbeam.sh -> build\lib.win-amd64-cpython-310\fairseq\examples\wav2vec\unsupervised\kaldi_self_train\st\local
      copying fairseq\examples\wav2vec\unsupervised\kaldi_self_train\st\local\unsup_select.py -> build\lib.win-amd64-cpython-310\fairseq\examples\wav2vec\unsupervised\kaldi_self_train\st\local
      copying fairseq\examples\wav2vec\unsupervised\kaldi_self_train\st\local\unsup_select_decode.sh -> build\lib.win-amd64-cpython-310\fairseq\examples\wav2vec\unsupervised\kaldi_self_train\st\local
      copying fairseq\examples\wav2vec\unsupervised\kaldi_self_train\st\local\unsup_select_decode_word.sh -> build\lib.win-amd64-cpython-310\fairseq\examples\wav2vec\unsupervised\kaldi_self_train\st\local
      creating build\lib.win-amd64-cpython-310\fairseq\examples\wav2vec\unsupervised\kaldi_self_train\st\steps_gan
      copying fairseq\examples\wav2vec\unsupervised\kaldi_self_train\st\steps_gan\train_deltas.sh -> build\lib.win-amd64-cpython-310\fairseq\examples\wav2vec\unsupervised\kaldi_self_train\st\steps_gan
      copying fairseq\examples\wav2vec\unsupervised\kaldi_self_train\st\steps_gan\train_lda_mllt.sh -> build\lib.win-amd64-cpython-310\fairseq\examples\wav2vec\unsupervised\kaldi_self_train\st\steps_gan
      copying fairseq\examples\wav2vec\unsupervised\kaldi_self_train\st\steps_gan\train_sat.sh -> build\lib.win-amd64-cpython-310\fairseq\examples\wav2vec\unsupervised\kaldi_self_train\st\steps_gan
      creating build\lib.win-amd64-cpython-310\fairseq\examples\wav2vec\unsupervised\scripts
      copying fairseq\examples\wav2vec\unsupervised\scripts\apply_pca.py -> build\lib.win-amd64-cpython-310\fairseq\examples\wav2vec\unsupervised\scripts
      copying fairseq\examples\wav2vec\unsupervised\scripts\copy_labels.py -> build\lib.win-amd64-cpython-310\fairseq\examples\wav2vec\unsupervised\scripts
      copying fairseq\examples\wav2vec\unsupervised\scripts\filter_lexicon.py -> build\lib.win-amd64-cpython-310\fairseq\examples\wav2vec\unsupervised\scripts
      copying fairseq\examples\wav2vec\unsupervised\scripts\filter_tsv.py -> build\lib.win-amd64-cpython-310\fairseq\examples\wav2vec\unsupervised\scripts
      copying fairseq\examples\wav2vec\unsupervised\scripts\g2p_wrd_to_phn.py -> build\lib.win-amd64-cpython-310\fairseq\examples\wav2vec\unsupervised\scripts
      copying fairseq\examples\wav2vec\unsupervised\scripts\ltr_to_wrd.py -> build\lib.win-amd64-cpython-310\fairseq\examples\wav2vec\unsupervised\scripts
      copying fairseq\examples\wav2vec\unsupervised\scripts\mean_pool.py -> build\lib.win-amd64-cpython-310\fairseq\examples\wav2vec\unsupervised\scripts
      copying fairseq\examples\wav2vec\unsupervised\scripts\merge_clusters.py -> build\lib.win-amd64-cpython-310\fairseq\examples\wav2vec\unsupervised\scripts
      copying fairseq\examples\wav2vec\unsupervised\scripts\normalize_and_filter_text.py -> build\lib.win-amd64-cpython-310\fairseq\examples\wav2vec\unsupervised\scripts
      copying fairseq\examples\wav2vec\unsupervised\scripts\normalize_text.py -> build\lib.win-amd64-cpython-310\fairseq\examples\wav2vec\unsupervised\scripts
      copying fairseq\examples\wav2vec\unsupervised\scripts\pca.py -> build\lib.win-amd64-cpython-310\fairseq\examples\wav2vec\unsupervised\scripts
      copying fairseq\examples\wav2vec\unsupervised\scripts\phonemize_with_sil.py -> build\lib.win-amd64-cpython-310\fairseq\examples\wav2vec\unsupervised\scripts
      copying fairseq\examples\wav2vec\unsupervised\scripts\prepare_audio.sh -> build\lib.win-amd64-cpython-310\fairseq\examples\wav2vec\unsupervised\scripts
      copying fairseq\examples\wav2vec\unsupervised\scripts\prepare_audio_v2.sh -> build\lib.win-amd64-cpython-310\fairseq\examples\wav2vec\unsupervised\scripts
      copying fairseq\examples\wav2vec\unsupervised\scripts\prepare_text.sh -> build\lib.win-amd64-cpython-310\fairseq\examples\wav2vec\unsupervised\scripts
      copying fairseq\examples\wav2vec\unsupervised\scripts\prepare_timit.sh -> build\lib.win-amd64-cpython-310\fairseq\examples\wav2vec\unsupervised\scripts
      copying fairseq\examples\wav2vec\unsupervised\scripts\remove_silence.py -> build\lib.win-amd64-cpython-310\fairseq\examples\wav2vec\unsupervised\scripts
      copying fairseq\examples\wav2vec\unsupervised\scripts\vads.py -> build\lib.win-amd64-cpython-310\fairseq\examples\wav2vec\unsupervised\scripts
      copying fairseq\examples\wav2vec\unsupervised\scripts\wav2vec_apply_cluster_faiss.py -> build\lib.win-amd64-cpython-310\fairseq\examples\wav2vec\unsupervised\scripts
      copying fairseq\examples\wav2vec\unsupervised\scripts\wav2vec_cluster_faiss.py -> build\lib.win-amd64-cpython-310\fairseq\examples\wav2vec\unsupervised\scripts
      copying fairseq\examples\wav2vec\unsupervised\scripts\wav2vec_extract_features.py -> build\lib.win-amd64-cpython-310\fairseq\examples\wav2vec\unsupervised\scripts
      copying fairseq\examples\wav2vec\unsupervised\scripts\wer.py -> build\lib.win-amd64-cpython-310\fairseq\examples\wav2vec\unsupervised\scripts
      copying fairseq\examples\wav2vec\unsupervised\scripts\wrd_to_ltr.py -> build\lib.win-amd64-cpython-310\fairseq\examples\wav2vec\unsupervised\scripts
      creating build\lib.win-amd64-cpython-310\fairseq\examples\wav2vec\xlsr
      copying fairseq\examples\wav2vec\xlsr\README.md -> build\lib.win-amd64-cpython-310\fairseq\examples\wav2vec\xlsr
      creating build\lib.win-amd64-cpython-310\fairseq\examples\wav2vec\xlsr\config
      copying fairseq\examples\wav2vec\xlsr\config\finetune.yaml -> build\lib.win-amd64-cpython-310\fairseq\examples\wav2vec\xlsr\config
      creating build\lib.win-amd64-cpython-310\fairseq\examples\wmt19
      copying fairseq\examples\wmt19\README.md -> build\lib.win-amd64-cpython-310\fairseq\examples\wmt19
      creating build\lib.win-amd64-cpython-310\fairseq\examples\wmt20
      copying fairseq\examples\wmt20\README.md -> build\lib.win-amd64-cpython-310\fairseq\examples\wmt20
      creating build\lib.win-amd64-cpython-310\fairseq\examples\wmt21
      copying fairseq\examples\wmt21\eval.sh -> build\lib.win-amd64-cpython-310\fairseq\examples\wmt21
      copying fairseq\examples\wmt21\README.md -> build\lib.win-amd64-cpython-310\fairseq\examples\wmt21
      creating build\lib.win-amd64-cpython-310\fairseq\examples\wmt21\scripts
      copying fairseq\examples\wmt21\scripts\normalize-punctuation.perl -> build\lib.win-amd64-cpython-310\fairseq\examples\wmt21\scripts
      copying fairseq\examples\wmt21\scripts\replace-unicode-punctuation.perl -> build\lib.win-amd64-cpython-310\fairseq\examples\wmt21\scripts
      creating build\lib.win-amd64-cpython-310\fairseq\examples\womens_bios
      copying fairseq\examples\womens_bios\query_occupations_from_wikidata.py -> build\lib.win-amd64-cpython-310\fairseq\examples\womens_bios
      copying fairseq\examples\womens_bios\README.md -> build\lib.win-amd64-cpython-310\fairseq\examples\womens_bios
      creating build\lib.win-amd64-cpython-310\fairseq\examples\xformers
      copying fairseq\examples\xformers\README.md -> build\lib.win-amd64-cpython-310\fairseq\examples\xformers
      creating build\lib.win-amd64-cpython-310\fairseq\examples\xglm
      copying fairseq\examples\xglm\model_card.md -> build\lib.win-amd64-cpython-310\fairseq\examples\xglm
      copying fairseq\examples\xglm\README.md -> build\lib.win-amd64-cpython-310\fairseq\examples\xglm
      creating build\lib.win-amd64-cpython-310\fairseq\examples\xlmr
      copying fairseq\examples\xlmr\README.md -> build\lib.win-amd64-cpython-310\fairseq\examples\xlmr
      creating build\lib.win-amd64-cpython-310\fairseq\examples\xmod
      copying fairseq\examples\xmod\preprocess_nli.py -> build\lib.win-amd64-cpython-310\fairseq\examples\xmod
      copying fairseq\examples\xmod\README.md -> build\lib.win-amd64-cpython-310\fairseq\examples\xmod
      copying fairseq\config\config.yaml -> build\lib.win-amd64-cpython-310\fairseq\config
      creating build\lib.win-amd64-cpython-310\fairseq\config\model
      creating build\lib.win-amd64-cpython-310\fairseq\config\model\transformer_lm
      copying fairseq\config\model\transformer_lm\transformer_lm_baevski_gbw.yaml -> build\lib.win-amd64-cpython-310\fairseq\config\model\transformer_lm
      copying fairseq\config\model\transformer_lm\transformer_lm_baevski_wiki103.yaml -> build\lib.win-amd64-cpython-310\fairseq\config\model\transformer_lm
      copying fairseq\config\model\transformer_lm\transformer_lm_big.yaml -> build\lib.win-amd64-cpython-310\fairseq\config\model\transformer_lm
      copying fairseq\config\model\transformer_lm\transformer_lm_gbw.yaml -> build\lib.win-amd64-cpython-310\fairseq\config\model\transformer_lm
      copying fairseq\config\model\transformer_lm\transformer_lm_gpt.yaml -> build\lib.win-amd64-cpython-310\fairseq\config\model\transformer_lm
      copying fairseq\config\model\transformer_lm\transformer_lm_gpt2_big.yaml -> build\lib.win-amd64-cpython-310\fairseq\config\model\transformer_lm
      copying fairseq\config\model\transformer_lm\transformer_lm_gpt2_medium.yaml -> build\lib.win-amd64-cpython-310\fairseq\config\model\transformer_lm
      copying fairseq\config\model\transformer_lm\transformer_lm_gpt2_small.yaml -> build\lib.win-amd64-cpython-310\fairseq\config\model\transformer_lm
      copying fairseq\config\model\transformer_lm\transformer_lm_wiki103.yaml -> build\lib.win-amd64-cpython-310\fairseq\config\model\transformer_lm
      creating build\lib.win-amd64-cpython-310\fairseq\config\model\wav2vec
      copying fairseq\config\model\wav2vec\vq_wav2vec_gumbel.yaml -> build\lib.win-amd64-cpython-310\fairseq\config\model\wav2vec
      creating build\lib.win-amd64-cpython-310\fairseq\config\model\wav2vec2
      copying fairseq\config\model\wav2vec2\wav2vec2_base.yaml -> build\lib.win-amd64-cpython-310\fairseq\config\model\wav2vec2
      copying fairseq\config\model\wav2vec2\wav2vec2_large.yaml -> build\lib.win-amd64-cpython-310\fairseq\config\model\wav2vec2
      running build_ext
      cythoning fairseq/data/data_utils_fast.pyx to fairseq/data\data_utils_fast.cpp
      cythoning fairseq/data/token_block_utils_fast.pyx to fairseq/data\token_block_utils_fast.cpp
      building 'fairseq.libbleu' extension
      creating build\temp.win-amd64-cpython-310
      creating build\temp.win-amd64-cpython-310\Release
      creating build\temp.win-amd64-cpython-310\Release\fairseq
      creating build\temp.win-amd64-cpython-310\Release\fairseq\clib
      creating build\temp.win-amd64-cpython-310\Release\fairseq\clib\libbleu
      cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\nasho\AppData\Local\Programs\Python\Python310\include -IC:\Users\nasho\AppData\Local\Programs\Python\Python310\Include /EHsc /Tpfairseq/clib/libbleu/libbleu.cpp /Fobuild\temp.win-amd64-cpython-310\Release\fairseq/clib/libbleu/libbleu.obj -std=c++11 -O3
      "cl.exe" ­Ґ пў«пҐвбп ў­гваҐ­­Ґ© Ё«Ё ў­Ґи­Ґ©
      Є®¬ ­¤®©, ЁбЇ®«­пҐ¬®© Їа®Ја ¬¬®© Ё«Ё Ї ЄҐв­л¬ д ©«®¬.
      error: command 'cl.exe' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fairseq
Failed to build fairseq
ERROR: Could not build wheels for fairseq, which is required to install pyproject.toml-based projects

I tried update SDK
tried install microsoft visual studio build tools
tried install fairseq from repository in github

maybe i didnt install something in visual studio

![изображение](https://github.com/Mangio621/Mangio-RVC-Fork/assets/82266003/0f831309-d2de-44ed-9210-71bdb2a637a7)

**Comment by Mangio621** [comment]
Visual studio with RVC dependencies are out of the scope of what I can handle. Does the original RVC repo reproduce the same issues? If so, please consider speaking with the main RVC devs. I'm not sure RVC is intended to be used with Visual Studio.

**Comment by ZarBoy68** [comment]
> 

I got the same thing on the original repository. I sent my mistake there. I hope they will answer me...
