### ISSUE TITLE
ERROR: No matching distribution found for onnxruntime-gpu

### ISSUE THREAD

**Issue by dexbyte** [Mangio621/Mangio-RVC-Fork#9]
Installing requirements on M1 Mac give these errors, any way to fix it?

```
ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu (from versions: none)
ERROR: No matching distribution found for onnxruntime-gpu
```

**Comment by dexbyte** [comment]
Found a way to solve this, but I am not sure if it will work since I am not aware of the code. Please confirm :) 

`pip install onnxruntime-silicon`

**Comment by Mangio621** [comment]
I think mac systems have some trouble with specifically onnxruntime-gpu. I'm not too sure. You might want to open this issue on the original RVC repo as i havent added this dependency here. I think you're right, you might need to use onnxruntime-silicon however as im sure the dependency has code exactly for m1 chips etc whereas -gpu doesn't have any m1 support.
